/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoundingCommunityRouteImport } from './routes/founding-community'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as WhatWeOfferRouteImport } from './routes/what-we-offer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundingCommunityRoute = FoundingCommunityRouteImport.update({
  id: '/founding-community',
  path: '/founding-community',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeOfferRoute = WhatWeOfferRouteImport.update({
  id: '/what-we-offer',
  path: '/what-we-offer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/founding-community': typeof FoundingCommunityRoute
  '/investors': typeof InvestorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/waitlist': typeof WaitlistRoute
  '/what-we-offer': typeof WhatWeOfferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/founding-community': typeof FoundingCommunityRoute
  '/investors': typeof InvestorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/waitlist': typeof WaitlistRoute
  '/what-we-offer': typeof WhatWeOfferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/founding-community': typeof FoundingCommunityRoute
  '/investors': typeof InvestorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/waitlist': typeof WaitlistRoute
  '/what-we-offer': typeof WhatWeOfferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/founding-community'
    | '/investors'
    | '/sitemap.xml'
    | '/vision'
    | '/waitlist'
    | '/what-we-offer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/founding-community'
    | '/investors'
    | '/sitemap.xml'
    | '/vision'
    | '/waitlist'
    | '/what-we-offer'
  id:
    | '__root__'
    | '/'
    | '/founding-community'
    | '/investors'
    | '/sitemap.xml'
    | '/vision'
    | '/waitlist'
    | '/what-we-offer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoundingCommunityRoute: typeof FoundingCommunityRoute
  InvestorsRoute: typeof InvestorsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisionRoute: typeof VisionRoute
  WaitlistRoute: typeof WaitlistRoute
  WhatWeOfferRoute: typeof WhatWeOfferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founding-community': {
      id: '/founding-community'
      path: '/founding-community'
      fullPath: '/founding-community'
      preLoaderRoute: typeof FoundingCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-offer': {
      id: '/what-we-offer'
      path: '/what-we-offer'
      fullPath: '/what-we-offer'
      preLoaderRoute: typeof WhatWeOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoundingCommunityRoute: FoundingCommunityRoute,
  InvestorsRoute: InvestorsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisionRoute: VisionRoute,
  WaitlistRoute: WaitlistRoute,
  WhatWeOfferRoute: WhatWeOfferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
